export const COURSE_LIST_REQUEST = 'COURSE_LIST_REQUEST';
export const COURSE_LIST_SUCCESS = 'COURSE_LIST_SUCCESS';
export const COURSE_LIST_FAIL = 'COURSE_LIST_FAIL';

export const COURSE_DEPT_LIST_REQUEST = 'COURSE_DEPT_REQUEST';
export const COURSE_DEPT_SUCCESS = 'COURSE_DEPT_SUCCESS';
export const COURSE_DEPT_FAIL = 'COURSE_DEPT_FAIL';

export const COURSE_ADD_MARKS_REQUEST = 'COURSE_ADD_MARKS_REQUEST';
export const COURSE_ADD_MARKS_SUCCESS = 'COURSE_ADD_MARKS_SUCCESS';
export const COURSE_ADD_MARKS_FAIL = 'COURSE_ADD_MARKS_FAIL';

export const COURSE_MARK_LIST_REQUEST = 'COURSE_MARK_LIST_REQUEST';
export const COURSE_MARK_LIST_SUCCESS = 'COURSE_MARK_LIST_SUCCESS';
export const COURSE_MARK_LIST_FAIL = 'COURSE_MARK_LIST_FAIL';

export const COURSE_MARK_UPDATE_REQUEST = 'COURSE_MARK_UPDATE_REQUEST';
export const COURSE_MARK_UPDATE_SUCCESS = 'COURSE_MARK_UPDATE_SUCCESS';
export const COURSE_MARK_UPDATE_FAIL = 'COURSE_MARK_UPDATE_FAIL';
export const COURSE_MARK_UPDATE_RESET = 'COURSE_MARK_UPDATE_RESET';

export const COURSE_MARK_DETAILS_REQUEST = 'COURSE_MARK_DETAILS_REQUEST';
export const COURSE_MARK_DETAILS_SUCCESS = 'COURSE_MARK_DETAILS_SUCCESS';
export const COURSE_MARK_DETAILS_FAIL = 'COURSE_MARK_DETAILS_FAIL';
export const COURSE_MARK_DETAILS_RESET = 'COURSE_MARK_DETAILS_RESET';
