export const COURSE_LIST_REQUEST = 'COURSE_LIST_REQUEST';
export const COURSE_LIST_SUCCESS = 'COURSE_LIST_SUCCESS';
export const COURSE_LIST_FAIL = 'COURSE_LIST_FAIL';

export const COURSE_ADD_MARKS_REQUEST = 'COURSE_ADD_MARKS_REQUEST';
export const COURSE_ADD_MARKS_SUCCESS = 'COURSE_ADD_MARKS_SUCCESS';
export const COURSE_ADD_MARKS_FAIL = 'COURSE_ADD_MARKS_FAIL';

export const COURSE_MARK_LIST_REQUEST = 'COURSE_MARK_LIST_REQUEST';
export const COURSE_MARK_LIST_SUCCESS = 'COURSE_MARK_LIST_SUCCESS';
export const COURSE_MARK_LIST_FAIL = 'COURSE_MARK_LIST_FAIL';
