export const COURSE_LIST_REQUEST = 'COURSE_LIST_REQUEST';
export const COURSE_LIST_SUCCESS = 'COURSE_LIST_SUCCESS';
export const COURSE_LIST_FAIL = 'COURSE_LIST_FAIL';

export const COURSE_DEPT_LIST_REQUEST = 'COURSE_DEPT_LIST_REQUEST';
export const COURSE_DEPT_LIST_SUCCESS = 'COURSE_DEPT_LIST_SUCCESS';
export const COURSE_DEPT_LIST_FAIL = 'COURSE_DEPT_LIST_FAIL';

export const COURSE_ADD_MARKS_REQUEST = 'COURSE_ADD_MARKS_REQUEST';
export const COURSE_ADD_MARKS_SUCCESS = 'COURSE_ADD_MARKS_SUCCESS';
export const COURSE_ADD_MARKS_FAIL = 'COURSE_ADD_MARKS_FAIL';

export const COURSE_MARK_LIST_REQUEST = 'COURSE_MARK_LIST_REQUEST';
export const COURSE_MARK_LIST_SUCCESS = 'COURSE_MARK_LIST_SUCCESS';
export const COURSE_MARK_LIST_FAIL = 'COURSE_MARK_LIST_FAIL';

export const COURSE_MARK_UPDATE_REQUEST = 'COURSE_MARK_UPDATE_REQUEST';
export const COURSE_MARK_UPDATE_SUCCESS = 'COURSE_MARK_UPDATE_SUCCESS';
export const COURSE_MARK_UPDATE_FAIL = 'COURSE_MARK_UPDATE_FAIL';
export const COURSE_MARK_UPDATE_RESET = 'COURSE_MARK_UPDATE_RESET';

export const COURSE_MARK_DETAILS_REQUEST = 'COURSE_MARK_DETAILS_REQUEST';
export const COURSE_MARK_DETAILS_SUCCESS = 'COURSE_MARK_DETAILS_SUCCESS';
export const COURSE_MARK_DETAILS_FAIL = 'COURSE_MARK_DETAILS_FAIL';
export const COURSE_MARK_DETAILS_RESET = 'COURSE_MARK_DETAILS_RESET';

export const GRADE_RANGE_UPDATE_REQUEST = 'GRADE_RANGE_UPDATE_REQUEST';
export const GRADE_RANGE_UPDATE_SUCCESS = 'GRADE_RANGE_UPDATE_SUCCESS';
export const GRADE_RANGE_UPDATE_FAIL = 'GRADE_RANGE_UPDATE_FAIL';
export const GRADE_RANGE_UPDATE_RESET = 'GRADE_RANGE_UPDATE_RESET';

export const GRADE_RANGE_DETAILS_REQUEST = 'GRADE_RANGE_DETAILS_REQUEST';
export const GRADE_RANGE_DETAILS_SUCCESS = 'GRADE_RANGE_DETAILS_SUCCESS';
export const GRADE_RANGE_DETAILS_FAIL = 'GRADE_RANGE_DETAILS_FAIL';
export const GRADE_RANGE_DETAILS_RESET = 'GRADE_RANGE_DETAILS_RESET';

export const RANGE_DETAILS_REQUEST = 'RANGE_DETAILS_REQUEST';
export const RANGE_DETAILS_SUCCESS = 'RANGE_DETAILS_SUCCESS';
export const RANGE_DETAILS_FAIL = 'RANGE_DETAILS_FAIL';
export const RANGE_DETAILS_RESET = 'RANGE_DETAILS_RESET';

export const ALL_GRADE_RANGE_DETAILS_REQUEST =
  'ALL_GRADE_RANGE_DETAILS_REQUEST';
export const ALL_GRADE_RANGE_DETAILS_SUCCESS =
  'ALL_GRADE_RANGE_DETAILS_SUCCESS';
export const ALL_GRADE_RANGE_DETAILS_FAIL = 'ALL_GRADE_RANGE_DETAILS_FAIL';
export const ALL_GRADE_RANGE_DETAILS_RESET = 'ALL_GRADE_RANGE_DETAILS_RESET';
