export const FACULTY_REGISTER_REQUEST = 'FACULTY_REGISTER_REQUEST';
export const FACULTY_REGISTER_SUCCESS = 'FACULTY_REGISTER_SUCCESS';
export const FACULTY_REGISTER_FAIL = 'FACULTY_REGISTER_FAIL';

export const FACULTY_LOGIN_REQUEST = 'FACULTY_LOGIN_REQUEST';
export const FACULTY_LOGIN_SUCCESS = 'FACULTY_LOGIN_SUCCESS';
export const FACULTY_LOGIN_FAIL = 'FACULTY_LOGIN_FAIL';
export const FACULTY_LOGOUT = 'FACULTY_LOGOUT';
