export const FACULTY_REGISTER_REQUEST = 'FACULTY_REGISTER_REQUEST';
export const FACULTY_REGISTER_SUCCESS = 'FACULTY_REGISTER_SUCCESS';
export const FACULTY_REGISTER_FAIL = 'FACULTY_REGISTER_FAIL';

export const FACULTY_LOGIN_REQUEST = 'FACULTY_LOGIN_REQUEST';
export const FACULTY_LOGIN_SUCCESS = 'FACULTY_LOGIN_SUCCESS';
export const FACULTY_LOGIN_FAIL = 'FACULTY_LOGIN_FAIL';
export const FACULTY_LOGOUT = 'FACULTY_LOGOUT';

export const FACULTY_LIST_REQUEST = 'FACULTY_LIST_REQUEST';
export const FACULTY_LIST_SUCCESS = 'FACULTY_LIST_SUCCESS';
export const FACULTY_LIST_FAIL = 'FACULTY_LIST_FAIL';

export const ADVISER_BATCH_LIST_REQUEST = 'ADVISER_BATCH_LIST_REQUEST';
export const ADVISER_BATCH_LIST_SUCCESS = 'ADVISER_BATCH_LIST_SUCCESS';
export const ADVISER_BATCH_LIST_FAIL = 'ADVISER_BATCH_LIST_FAIL';

export const FACULTY_PROFILE_UPDATE_REQUEST = 'FACULTY_PROFILE_UPDATE_REQUEST';
export const FACULTY_PROFILE_UPDATE_SUCCESS = 'FACULTY_PROFILE_UPDATE_SUCCESS';
export const FACULTY_PROFILE_UPDATE_FAIL = 'FACULTY_PROFILE_UPDATE_FAIL';
export const FACULTY_PROFILE_UPDATE_RESET = 'FACULTY_PROFILE_UPDATE_RESET';
