export const GRACEMARK_CREATE_REQUEST = 'GRACEMARK_CREATE_REQUEST';
export const GRACEMARK_CREATE_SUCCESS = 'GRACEMARK_CREATE_SUCCESS';
export const GRACEMARK_CREATE_FAIL = 'GRACEMARK_CREATE_FAIL';
export const GRACEMARK_CREATE_RESET = 'GRACEMARK_CREATE_RESET';

export const GRACEMARK_LIST_REQUEST = 'GRACEMARK_LIST_REQUEST';
export const GRACEMARK_LIST_SUCCESS = 'GRACEMARK_LIST_SUCCESS';
export const GRACEMARK_LIST_FAIL = 'GRACEMARK_LIST_FAIL';

export const GRACEMARK_DETAILS_REQUEST = 'GRACEMARK_DETAILS_REQUEST';
export const GRACEMARK_DETAILS_SUCCESS = 'GRACEMARK_DETAILS_SUCCESS';
export const GRACEMARK_DETAILS_FAIL = 'GRACEMARK_DETAILS_FAIL';
export const GRACEMARK_DETAILS_RESET = 'GRACEMARK_DETAILS_RESET';

export const GRACEMARK_DELETE_REQUEST = 'GRACEMARK_DELETE_REQUEST';
export const GRACEMARK_DELETE_SUCCESS = 'GRACEMARK_DELETE_SUCCESS';
export const GRACEMARK_DELETE_FAIL = 'GRACEMARK_DELETE_FAIL';

export const GRACEMARK_UPDATE_REQUEST = 'GRACEMARK_UPDATE_REQUEST';
export const GRACEMARK_UPDATE_SUCCESS = 'GRACEMARK_UPDATE_SUCCESS';
export const GRACEMARK_UPDATE_FAIL = 'GRACEMARK_UPDATE_FAIL';
export const GRACEMARK_UPDATE_RESET = 'GRACEMARK_UPDATE_RESET';
