export const GRACEMARK_CREATE_REQUEST = 'GRACEMARK_CREATE_REQUEST';
export const GRACEMARK_CREATE_SUCCESS = 'GRACEMARK_CREATE_SUCCESS';
export const GRACEMARK_CREATE_FAIL = 'GRACEMARK_CREATE_FAIL';
export const GRACEMARK_CREATE_RESET = 'GRACEMARK_CREATE_RESET';

export const GRACEMARK_LIST_REQUEST = 'GRACEMARK_LIST_REQUEST';
export const GRACEMARK_LIST_SUCCESS = 'GRACEMARK_LIST_SUCCESS';
export const GRACEMARK_LIST_FAIL = 'GRACEMARK_LIST_FAIL';


