export const STUDENT_REGISTER_REQUEST = 'STUDENT_REGISTER_REQUEST';
export const STUDENT_REGISTER_SUCCESS = 'STUDENT_REGISTER_SUCCESS';
export const STUDENT_REGISTER_FAIL = 'STUDENT_REGISTER_FAIL';

export const STUDENT_LOGIN_REQUEST = 'STUDENT_LOGIN_REQUEST';
export const STUDENT_LOGIN_SUCCESS = 'STUDENT_LOGIN_SUCCESS';
export const STUDENT_LOGIN_FAIL = 'STUDENT_LOGIN_FAIL';
export const STUDENT_LOGOUT = 'STUDENT_LOGOUT';

export const STUDENT_LIST_REQUEST = 'STUDENT_LIST_REQUEST';
export const STUDENT_LIST_SUCCESS = 'STUDENT_LIST_SUCCESS';
export const STUDENT_LIST_FAIL = 'STUDENT_LIST_FAIL';

export const REQUEST_ADD_REQUEST = 'REQUEST_LIST_REQUEST';
export const REQUEST_ADD_SUCCESS = 'REQUEST_LIST_SUCCESS';
export const REQUEST_ADD_FAIL = 'REQUEST_LIST_FAIL';