export const STUDENT_REGISTER_REQUEST = 'STUDENT_REGISTER_REQUEST';
export const STUDENT_REGISTER_SUCCESS = 'STUDENT_REGISTER_SUCCESS';
export const STUDENT_REGISTER_FAIL = 'STUDENT_REGISTER_FAIL';

export const STUDENT_LOGIN_REQUEST = 'STUDENT_LOGIN_REQUEST';
export const STUDENT_LOGIN_SUCCESS = 'STUDENT_LOGIN_SUCCESS';
export const STUDENT_LOGIN_FAIL = 'STUDENT_LOGIN_FAIL';
export const STUDENT_LOGOUT = 'STUDENT_LOGOUT';

export const STUDENT_LIST_REQUEST = 'STUDENT_LIST_REQUEST';
export const STUDENT_LIST_SUCCESS = 'STUDENT_LIST_SUCCESS';
export const STUDENT_LIST_FAIL = 'STUDENT_LIST_FAIL';

export const STUDENT_LIST_COURSE_REQUEST = 'STUDENT_LIST_COURSE_REQUEST';
export const STUDENT_LIST_COURSE_SUCCESS = 'STUDENT_LIST_COURSE_SUCCESS';
export const STUDENT_LIST_COURSE_FAIL = 'STUDENT_LIST_COURSE_FAIL';

export const REQUEST_ADD_REQUEST = 'REQUEST_ADD_REQUEST';
export const REQUEST_ADD_SUCCESS = 'REQUEST_ADD_SUCCESS';
export const REQUEST_ADD_FAIL = 'REQUEST_ADD_FAIL';
export const REQUEST_ADD_RESET = 'REQUEST_ADD_RESET';

export const REQUEST_ACCEPT_REQUEST = 'REQUEST_ACCEPT_REQUEST';
export const REQUEST_ACCEPT_SUCCESS = 'REQUEST_ACCEPT_SUCCESS';
export const REQUEST_ACCEPT_FAIL = 'REQUEST_ACCEPT_FAIL';

export const REQUEST_REJECT_REQUEST = 'REQUEST_REJECT_REQUEST';
export const REQUEST_REJECT_SUCCESS = 'REQUEST_REJECT_SUCCESS';
export const REQUEST_REJECT_FAIL = 'REQUEST_REJECT_FAIL';
